// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumfsuRCcX2d5AcE0VT_JNHZLG9Ft-rPA',
    appId: '1:619385997721:web:5eccb57003a7645341eb08',
    messagingSenderId: '619385997721',
    projectId: 'tourghana-88aa8',
    authDomain: 'tourghana-88aa8.firebaseapp.com',
    storageBucket: 'tourghana-88aa8.appspot.com',
    measurementId: 'G-02DQWYKGYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa565pBPX_25AqXAzaNel98ahUFiR3GJA',
    appId: '1:619385997721:android:b00bd6ddc05b076541eb08',
    messagingSenderId: '619385997721',
    projectId: 'tourghana-88aa8',
    storageBucket: 'tourghana-88aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB89eQtd5pNr2eduDREjn7Llx-PFLHDekU',
    appId: '1:619385997721:ios:8f1742058eef6f2b41eb08',
    messagingSenderId: '619385997721',
    projectId: 'tourghana-88aa8',
    storageBucket: 'tourghana-88aa8.appspot.com',
    iosBundleId: 'com.example.tourghana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB89eQtd5pNr2eduDREjn7Llx-PFLHDekU',
    appId: '1:619385997721:ios:8f1742058eef6f2b41eb08',
    messagingSenderId: '619385997721',
    projectId: 'tourghana-88aa8',
    storageBucket: 'tourghana-88aa8.appspot.com',
    iosBundleId: 'com.example.tourghana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBumfsuRCcX2d5AcE0VT_JNHZLG9Ft-rPA',
    appId: '1:619385997721:web:6f0b79217bca186941eb08',
    messagingSenderId: '619385997721',
    projectId: 'tourghana-88aa8',
    authDomain: 'tourghana-88aa8.firebaseapp.com',
    storageBucket: 'tourghana-88aa8.appspot.com',
    measurementId: 'G-MD50Y7JKTR',
  );
}
